POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "bullshit$0200"
}

###
GET http://localhost:8000/api/v1/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMTIwOTNlMC1lODBlLTQ4NzctODE0OS0yNmE4NTNkZGI1NjEiLCJyZWZyZXNoIjpmYWxzZSwiaWF0IjoxNzU2OTc3NjE1LjI3NTkzNiwiZXhwIjoxNzU3MTkzNjE1LjI3NTkzNn0.ritONHWs1C_-qXtM22N6tUG0yA8O_7HXaF5e55YEevM

###


