"""Add is_staff field to User model

Revision ID: 58328a446c4a
Revises: 3c242e501ef7
Create Date: 2025-09-04 07:24:53.127837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58328a446c4a'
down_revision: Union[str, Sequence[str], None] = '3c242e501ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE \"user\" SET is_staff = false WHERE is_staff IS NULL")
    
    # Now make it non-nullable
    op.alter_column('user', 'is_staff', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_staff')
    # ### end Alembic commands ###
